### PR TITLE
Update application-tokens.md

### PR DESCRIPTION
**Pull request by amduboi2**
This statement is hard to decipher. I'm trying to update it with what I think the author meant to say.

### CODE REVIEW

**Comment by kaltura-hooks** [comment]
Hi @amduboi2,
Thank you for contributing this pull request!
Please sign the Kaltura CLA so we can review and merge your contribution.
Learn more at http://bit.ly/KalturaContrib

**Comment by jessp01** [comment]
Hi @amduboi2,

Actually, the original statement is correct.
> Note: While a user ID *can* be added to an App Token during session generation (if no user ID was specified in the App Token creation), privileges CANNOT be added during session generation. 

Upon the creation of an app token object, one may specify a user ID as well as restrict the privileges this token will have (or, in other words, the service->action pairs this token can be used with). If no user ID was specified when making the token creation request (`appToken.add()`), one may be specified when generating a session (`appToken.startSession()`). However, the privileges cannot be altered when generating a session with said token.

Cheers,

**Comment by amduboi2** [comment]
ok, my apologies on that!
________________________________

**Comment by jessp01** [comment]
No need to apologise. I hope things are clearer now? If there are no additional questions on this one, please close the pull?
Thanks,

**Pull request closed without merging**
